//  geoip.c
//  geoip
//
//  Created by Dr. Rolf Jansen on 2016-07-17.
//  Copyright © 2016 projectworld.net. All rights reserved.
//
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//
//  1. Redistributions of source code must retain the above copyright notice,
//     this list of conditions and the following disclaimer.
//
//  2. Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
//  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
//  AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER
//  OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
//  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
//  IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
//  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/time.h>

#include "store.h"


void usage(const char *executable)
{
   const char *r = executable + strvlen(executable);
   while (--r >= executable && *r != '/'); r++;
   printf("%s v1.1 ("SVNREV"), Copyright © 2016 Dr. Rolf Jansen\n\n", r);
   printf("Usage:\n\n");
   printf("1) look-up the country code belonging to an IP address given by the last command line argument:\n\n");
   printf("   %s [-r bstfile] [-h] <IP address>\n", r);
   printf("      <IP address>      an IPv4 or an IPv6 address to be looked-up.\n\n");
   printf("2) generate a sorted list of IP address/masklen pairs per country code, formatted as ipfw table construction directives:\n\n");
   printf("   %s -t [CC:DD:EE:..] [-n table number] [-v table value] [-x offset] [-4] [-6] [-p] [-r bstfile] [-h]\n\n", r);
   printf("      -t [CC:DD:EE:..]  output all IP address/masklen pairs belonging to the listed countries, given by 2 letter\n");
   printf("                        capital country codes, separated by colon. An empty CC list means any country code.\n");
   printf("      -n table number   the ipfw table number between 0 and 65534 [default: 0].\n");
   printf("      -v table value    the 32-bit unsigned value of the ipfw table entry [default: 0].\n");
   printf("      -x offset         output the decimal encoded country code + offset as the table value:\n");
   printf("                        val = (C1 - 60)*1000 + C2*10 + offset -- 0 <= offset < 34735\n");
   printf("      -4                only process IPv4 address ranges.\n");
   printf("      -6                only process IPv6 address ranges.\n");
   printf("      -p                plain IP table generation, i.e. without ipfw construction directives, -n and -v flags are ignored.\n\n");
   printf("valid arguments in both usage forms:\n\n");
   printf("      -r bstfile        the path to the binary files (.v4 and .v6) with the consolidated IP ranges that has been.\n");
   printf("                        generated by the 'ipdb' tool [default: /usr/local/etc/ipdb/IPRanges/ipcc.bst].\n");
   printf("      -h                show these usage instructions.\n\n");
}


CCNode **CCTable  = NULL;
IP4Node *IP4Store = NULL;
IP6Node *IP6Store = NULL;

int main(int argc, char *argv[])
{
   bool plainFlag = false,
        ccValFlag = false,
        only4Flag = false,
        only6Flag = false;

   int32_t  ch,
            rc    = 1,
            tnum  = 0,
            toff  = 0;
   uint32_t tval  = 0;

   char *ccList   = NULL,
        *bstfname = "/usr/local/etc/ipdb/IPRanges/ipcc.bst",    // actually 2 files *.v4 and *.v6
        *cmd      = argv[0],
        *lastopt  = "";

   while ((ch = getopt(argc, argv, "t:n:pv:x:46r:h")) != -1)
   {
      switch (ch)
      {
         case 't':
            ccList = optarg;
            break;

         case 'n':
            tnum = (int32_t)strtol(optarg, NULL, 10);
            if (tnum < 0 || 65534 < tnum || tnum == 0 && errno == EINVAL)
            {
               lastopt = optarg;
               goto arg_err;
            }
            break;

         case 'p':
            plainFlag = true;
            break;

         case 'v':
            if (ccValFlag || (tval = (uint32_t)strtol(optarg, NULL, 10)) == 0 && errno == EINVAL)
            {
               lastopt = optarg;
               goto arg_err;
            }
            break;

         case 'x':
            if (tval || (toff = (int32_t)strtol(optarg, NULL, 10)) == 0 && errno == EINVAL || toff < 0 || 34735 < toff)
            {
               lastopt = optarg;
               goto arg_err;
            }
            ccValFlag = true;
            break;

         case '4':
            if (only6Flag)
               goto arg_err;
            only4Flag = true;
            break;

         case '6':
            if (only4Flag)
               goto arg_err;
            only6Flag = true;
            break;

         case 'r':
            bstfname = optarg;
            break;

         arg_err:
            printf("Incorrect argument:\n -%c %s, ...\n\n", ch, lastopt);
         default:
            rc = 1;
         case 'h':
            usage(cmd);
            return rc;
      }
   }

   argc -= optind;
   argv += optind;

   if (argc != 1 && !ccList)
   {
      printf("Wrong number of arguments:\n %s, ...\n\n", argv[0]);
      usage(cmd);
      return 1;
   }


   int    namelen = strvlen(bstfname);
   char  *inName  = strcpy(alloca(namelen+4), bstfname);
   FILE  *in;
   struct stat st;

   rc = 1;

//
// first usage form -- lookup the country code for a given IPv4 or IPv6 address
//
   if (ccList == NULL)
   {
      uint32_t  ipv4;
      uint128_t ipv6;
      if (ipv4 = ipv4_str2bin(argv[0]))
      {
         *(uint32_t *)&inName[namelen] = *(uint32_t *)".v4";
         if (stat(inName, &st) == noerr && st.st_size && (in = fopen(inName, "r")))
         {
            IP4Str ipstr_lo, ipstr_hi;
            IP4Set *sortedIP4Sets = allocate(st.st_size, false);
            if (sortedIP4Sets)
            {
               if (fread(sortedIP4Sets, st.st_size, 1, in))
               {
                  IP4Store = sortedIP4SetsToTree(sortedIP4Sets, 0, (int)(st.st_size/sizeof(IP4Set)) - 1);
                  IP4Node *node = findIP4Node(ipv4, IP4Store);
                  if (node)
                     printf("%s in %s - %s in %s\n\n", argv[0], ipv4_bin2str(node->lo, ipstr_lo), ipv4_bin2str(node->hi, ipstr_hi), (char *)&node->cc);
                  else
                     printf("%s not found.\n\n", argv[0]);

                  releaseIP4Tree(IP4Store);
                  rc = 0;
               }
               else
                  printf("IPv4 database file could not be loaded.\n\n");

               deallocate(VPR(sortedIP4Sets), false);
            }
            else
               printf("Not enough memory for loading the IPv4 database.\n\n");

            fclose(in);
         }
         else
            printf("IPv4 database file could not be found.\n\n");
      }

      else if (ipv6 = ipv6_str2bin(argv[0]))
      {
         *(uint32_t *)&inName[namelen] = *(uint32_t *)".v6";
         if (stat(inName, &st) == noerr && st.st_size && (in = fopen(inName, "r")))
         {
            IP6Str ipstr_lo, ipstr_hi;
            IP6Set *sortedIP6Sets = allocate(st.st_size, false);
            if (sortedIP6Sets)
            {
               if (fread(sortedIP6Sets, st.st_size, 1, in))
               {
                  IP6Store = sortedIP6SetsToTree(sortedIP6Sets, 0, (int)(st.st_size/sizeof(IP6Set)) - 1);
                  IP6Node *node = findIP6Node(ipv6, IP6Store);
                  if (node)
                     printf("%s in %s - %s in %s\n\n", argv[0], ipv6_bin2str(node->lo, ipstr_lo), ipv6_bin2str(node->hi, ipstr_hi), (char *)&node->cc);
                  else
                     printf("%s not found.\n\n", argv[0]);

                  releaseIP6Tree(IP6Store);
                  rc = 0;
               }
               else
                  printf("IPv6 database file could not be loaded.\n\n");

               deallocate(VPR(sortedIP6Sets), false);
            }
            else
               printf("Not enough memory for loading the IPv6 database.\n\n");

            fclose(in);
         }
         else
            printf("IPv6 database file could not be found.\n\n");
      }

      else
         printf("Invalid IP address.\n\n");
   }


//
// second usage form -- generate ipfw table construction directives
//
   else // (ccList != NULL)
   {
      if (CCTable = createCCTable())
      {
         int count = 0;
         char *cc = ccList;
         while (*cc)
         {
            int tl = taglen(cc);
            if (cc[tl] == ':')
               cc[tl++] = '\0';
            storeCC(CCTable, *(uint16_t *)uppercase(cc, 2));
            cc += tl;
         }

      //
      // IPv4 table generation
      //
         if (!only6Flag)
         {
            *(uint32_t *)&inName[namelen] = *(uint32_t *)".v4";
            if (stat(inName, &st) == noerr && st.st_size && (in = fopen(inName, "r")))
            {
               IP4Str ipstr;
               IP4Set *sortedIP4Sets = allocate(st.st_size, false);
               if (sortedIP4Sets)
               {
                  if (fread(sortedIP4Sets, st.st_size, 1, in))
                  {
                     int i, n = (int)(st.st_size/sizeof(IP4Set));
                     for (i = 0; i < n; i++)
                     {
                        if (!*ccList || findCC(CCTable, sortedIP4Sets[i][2]))
                        {
                           uint32_t k, ip = sortedIP4Sets[i][0];
                           do
                           {
                              int32_t m = intlb4(sortedIP4Sets[i][1] - ip + 1);
                              while (ip % (k = inteb4(m)))
                                 m--;

                              if (plainFlag)
                                 printf("%s/%d\n", ipv4_bin2str(ip, ipstr), 32 - m);
                              else if (tval != 0)
                                 printf("table %d add %s/%d %u\n", tnum, ipv4_bin2str(ip, ipstr), 32 - m, tval);
                              else if (ccValFlag)
                                 printf("table %d add %s/%d %d\n", tnum, ipv4_bin2str(ip, ipstr), 32 - m, ccEncode((uint16_t)sortedIP4Sets[i][2])+toff);
                              else
                                 printf("table %d add %s/%d\n",    tnum, ipv4_bin2str(ip, ipstr), 32 - m);

                              count++;
                           }
                           while ((ip += k) < sortedIP4Sets[i][1]);
                        }
                     }

                     rc = 0;
                  }
                  else
                     printf("IPv4 database file could not be loaded.\n\n");

                  deallocate(VPR(sortedIP4Sets), false);
               }
               else
                  printf("Not enough memory for loading the IPv4 database.\n\n");

               fclose(in);
            }
            else
               printf("IPv4 database file could not be found.\n\n");
         }

      //
      // IPv6 table generation
      //
         if (!only4Flag)
         {
            *(uint32_t *)&inName[namelen] = *(uint32_t *)".v6";
            if (stat(inName, &st) == noerr && st.st_size && (in = fopen(inName, "r")))
            {
               IP6Str ipstr;
               IP6Set *sortedIP6Sets = allocate(st.st_size, false);
               if (sortedIP6Sets)
               {
                  if (fread(sortedIP6Sets, st.st_size, 1, in))
                  {
                     int i, n = (int)(st.st_size/sizeof(IP6Set));
                     for (i = 0; i < n; i++)
                     {
                        if (!*ccList || findCC(CCTable, (uint32_t)sortedIP6Sets[i][2]))
                        {
                           uint128_t k, ip = sortedIP6Sets[i][0];
                           do
                           {
                              int32_t m = intlb6(sortedIP6Sets[i][1] - ip + 1);
                              while (ip % (k = inteb6(m)))
                                 m--;

                              if (plainFlag)
                                 printf("%s/%d\n", ipv6_bin2str(ip, ipstr), 128 - m);
                              else if (tval != 0)
                                 printf("table %d add %s/%d %u\n", tnum, ipv6_bin2str(ip, ipstr), 128 - m, tval);
                              else if (ccValFlag)
                                 printf("table %d add %s/%d %d\n", tnum, ipv6_bin2str(ip, ipstr), 128 - m, ccEncode((uint16_t)sortedIP6Sets[i][2])+toff);
                              else
                                 printf("table %d add %s/%d\n",    tnum, ipv6_bin2str(ip, ipstr), 128 - m);

                              count++;
                           }
                           while ((ip += k) < sortedIP6Sets[i][1]);
                        }
                     }

                     rc = 0;
                  }
                  else
                     printf("IPv6 database file could not be loaded.\n\n");

                  deallocate(VPR(sortedIP6Sets), false);
               }
               else
                  printf("Not enough memory for loading the IPv6 database.\n\n");

               fclose(in);
            }
            else
               printf("IPv6 database file could not be found.\n\n");
         }

         if (!count)
            printf("\n");

         releaseCCTable(CCTable);
      }
      else
         printf("Not enough memory.\n\n");
   }

   return rc;
}
